# Generated by Django 5.1.3 on 2025-12-14 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discovery', '0001_initial'),
        ('uploads', '0003_eventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConformanceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_version', models.CharField(choices=[('raw', 'Raw Data'), ('cleaned', 'Cleaned Data'), ('default', 'Default')], default='default', help_text='Which version of the log was used', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this conformance check was performed')),
                ('total_cases', models.IntegerField(help_text='Total number of cases analyzed')),
                ('compliant_cases', models.IntegerField(help_text='Number of cases that fit the model')),
                ('non_compliant_cases', models.IntegerField(help_text="Number of cases that don't fit the model")),
                ('compliant_percentage', models.FloatField(help_text='Percentage of compliant cases')),
                ('non_compliant_percentage', models.FloatField(help_text='Percentage of non-compliant cases')),
                ('compliant_case_ids', models.JSONField(blank=True, default=list, help_text='List of compliant case IDs')),
                ('non_compliant_case_ids', models.JSONField(blank=True, default=list, help_text='List of non-compliant case IDs')),
                ('discovered_model', models.ForeignKey(help_text='The process model checked against', on_delete=django.db.models.deletion.CASCADE, related_name='conformance_results', to='discovery.discoveredprocessmodel')),
                ('event_log', models.ForeignKey(help_text='The event log used for conformance checking', on_delete=django.db.models.deletion.CASCADE, related_name='conformance_results', to='uploads.eventlog')),
            ],
            options={
                'verbose_name': 'Conformance Result',
                'verbose_name_plural': 'Conformance Results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_log', 'discovered_model'], name='conformance_event_l_bb6539_idx'), models.Index(fields=['created_at'], name='conformance_created_60cbe7_idx')],
            },
        ),
    ]
