# Generated by Django 5.1.3 on 2026-01-04 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_algorithms',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed mining algorithms (empty = all allowed)'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_activated_at',
            field=models.DateTimeField(blank=True, help_text='When premium license was activated', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_expires_at',
            field=models.DateTimeField(blank=True, help_text='When premium license expires (null = lifetime)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_type',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', help_text="User's license type", max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='max_log_rows',
            field=models.IntegerField(default=1000, help_text='Maximum number of rows in event log (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_projects',
            field=models.IntegerField(default=3, help_text='Maximum number of projects (0 = unlimited)'),
        ),
        migrations.CreateModel(
            name='LicenseCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='License activation code', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this code can be used')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this code has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the code was used', null=True)),
                ('duration_days', models.IntegerField(blank=True, help_text='License duration in days (null = lifetime)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this code')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_license_codes', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, help_text='User who used this code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_license_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'License Code',
                'verbose_name_plural': 'License Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
