# Generated by Django 5.1.3 on 2025-12-09 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0003_eventlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredProcessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('alpha', 'Alpha Miner'), ('heuristics', 'Heuristics Miner'), ('inductive', 'Inductive Miner')], help_text='The discovery algorithm used', max_length=20)),
                ('source_version', models.CharField(choices=[('raw', 'Raw Data'), ('cleaned', 'Cleaned Data')], default='raw', help_text='Whether raw or cleaned log was used', max_length=10)),
                ('pnml_content', models.TextField(help_text='The Petri net in PNML XML format (for Groups 5 & 6)')),
                ('num_places', models.IntegerField(default=0, help_text='Number of places in the Petri net')),
                ('num_transitions', models.IntegerField(default=0, help_text='Number of transitions in the Petri net')),
                ('num_arcs', models.IntegerField(default=0, help_text='Number of arcs in the Petri net')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, help_text='When this model was discovered')),
                ('discovered_by', models.ForeignKey(blank=True, help_text='User who ran the discovery algorithm', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_models', to=settings.AUTH_USER_MODEL)),
                ('event_log', models.ForeignKey(help_text='The event log this model was discovered from', on_delete=django.db.models.deletion.CASCADE, related_name='discovered_models', to='uploads.eventlog')),
            ],
            options={
                'verbose_name': 'Discovered Process Model',
                'verbose_name_plural': 'Discovered Process Models',
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['event_log', 'algorithm'], name='discovery_d_event_l_aece9f_idx'), models.Index(fields=['event_log', 'source_version'], name='discovery_d_event_l_877648_idx')],
            },
        ),
    ]
