# Generated by Django 5.1.3 on 2025-12-22 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLogJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(help_text='The uploaded event log file (.xes or .csv)', upload_to='uploads/event_logs/%Y/%m/%d/')),
                ('original_filename', models.CharField(help_text='Original name of the uploaded file', max_length=255)),
                ('cleaning_enabled', models.BooleanField(default=False, help_text='Whether data cleaning was requested')),
                ('mining_method', models.CharField(choices=[('alpha', 'Alpha Miner'), ('heuristics', 'Heuristics Miner')], help_text='The process mining method to use', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='pending', help_text='Current job status', max_length=10)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('message', models.CharField(blank=True, help_text='Current status message', max_length=255)),
                ('error_message', models.TextField(blank=True, help_text='Error details if job failed')),
                ('output_map_image', models.ImageField(blank=True, help_text='Generated process map as PNG', null=True, upload_to='outputs/process_maps/%Y/%m/%d/')),
                ('output_map_svg', models.FileField(blank=True, help_text='Generated process map as SVG', null=True, upload_to='outputs/process_maps/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this job was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last status update time')),
                ('user', models.ForeignKey(help_text='User who uploaded this file', on_delete=django.db.models.deletion.CASCADE, related_name='event_log_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Log Job',
                'verbose_name_plural': 'Event Log Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='discovery_e_user_id_1134d4_idx'), models.Index(fields=['status', 'created_at'], name='discovery_e_status_5ddeaf_idx')],
            },
        ),
    ]
