# Generated by Django 5.1.3 on 2025-12-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_eventlogjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlogjob',
            name='project_name',
            field=models.CharField(blank=True, default='', help_text='User-defined project name', max_length=255),
        ),
    ]
