# Generated by Django 5.1.3 on 2025-12-23 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_eventlogjob_project_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(help_text='Temporarily stored CSV file', upload_to='temp_csv_imports/%Y/%m/%d/')),
                ('original_filename', models.CharField(help_text='Original CSV filename', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this session was created')),
                ('user', models.ForeignKey(help_text='User who uploaded this CSV', on_delete=django.db.models.deletion.CASCADE, related_name='csv_import_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CSV Import Session',
                'verbose_name_plural': 'CSV Import Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
