# Generated by Django 5.1.3 on 2026-01-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_csvimportsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvimportsession',
            name='project_name',
            field=models.CharField(blank=True, help_text='Project name for this import', max_length=255, null=True),
        ),
    ]
