# Generated by Django 4.2.27 on 2026-01-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConformanceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_file', models.CharField(max_length=255)),
                ('log_file', models.CharField(max_length=255)),
                ('timestamp_key_used', models.CharField(blank=True, default='', max_length=255)),
                ('total_cases', models.IntegerField()),
                ('compliant_cases', models.IntegerField()),
                ('non_compliant_cases', models.IntegerField()),
                ('compliant_percentage', models.FloatField()),
                ('non_compliant_percentage', models.FloatField()),
                ('log_fitness', models.FloatField(blank=True, null=True)),
                ('average_trace_fitness', models.FloatField(blank=True, null=True)),
                ('percentage_of_fitting_traces', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('summary_json_path', models.CharField(blank=True, default='', max_length=500)),
                ('compliant_csv_path', models.CharField(blank=True, default='', max_length=500)),
                ('non_compliant_csv_path', models.CharField(blank=True, default='', max_length=500)),
                ('pnml_path', models.CharField(blank=True, default='', max_length=500)),
                ('log_csv_path', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
