# Generated by Django 5.1.3 on 2025-11-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(help_text="Unique key for translation (e.g., 'user_id', 'welcome_message')", max_length=100, unique=True)),
                ('fa', models.CharField(help_text='Persian translation', max_length=500)),
                ('en', models.CharField(help_text='English translation', max_length=500)),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['phrase'],
            },
        ),
    ]
