# Generated by Django 5.2.8 on 2025-11-22 12:47

import django.db.models.deletion
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='فایل Event Log (CSV, XES)', storage=storages.backends.s3.S3Storage(), upload_to='raw_logs/')),
                ('original_filename', models.CharField(help_text='نام اصلی فایل آپلود شده', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='زمان آپلود')),
                ('file_size', models.BigIntegerField(blank=True, help_text='حجم فایل به بایت', null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='کاربر آپلودکننده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
                'db_table': 'event_logs',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
