# Generated by Django 5.1.3 on 2025-11-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='size_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
